// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/western_queen.proto

package western_queen

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// slave to master write wrong trace data
type WrongTraceDataRequest struct {
	TraceId              string   `protobuf:"bytes,1,opt,name=traceId,proto3" json:"traceId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WrongTraceDataRequest) Reset()         { *m = WrongTraceDataRequest{} }
func (m *WrongTraceDataRequest) String() string { return proto.CompactTextString(m) }
func (*WrongTraceDataRequest) ProtoMessage()    {}
func (*WrongTraceDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_567c35356db43e2a, []int{0}
}

func (m *WrongTraceDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WrongTraceDataRequest.Unmarshal(m, b)
}
func (m *WrongTraceDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WrongTraceDataRequest.Marshal(b, m, deterministic)
}
func (m *WrongTraceDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WrongTraceDataRequest.Merge(m, src)
}
func (m *WrongTraceDataRequest) XXX_Size() int {
	return xxx_messageInfo_WrongTraceDataRequest.Size(m)
}
func (m *WrongTraceDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WrongTraceDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WrongTraceDataRequest proto.InternalMessageInfo

func (m *WrongTraceDataRequest) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

// master to slave share wrong trace data
type ShareWrongTraceDataReturn struct {
	WrongTraceDataRequests []string `protobuf:"bytes,1,rep,name=wrongTraceDataRequests,proto3" json:"wrongTraceDataRequests,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *ShareWrongTraceDataReturn) Reset()         { *m = ShareWrongTraceDataReturn{} }
func (m *ShareWrongTraceDataReturn) String() string { return proto.CompactTextString(m) }
func (*ShareWrongTraceDataReturn) ProtoMessage()    {}
func (*ShareWrongTraceDataReturn) Descriptor() ([]byte, []int) {
	return fileDescriptor_567c35356db43e2a, []int{1}
}

func (m *ShareWrongTraceDataReturn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShareWrongTraceDataReturn.Unmarshal(m, b)
}
func (m *ShareWrongTraceDataReturn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShareWrongTraceDataReturn.Marshal(b, m, deterministic)
}
func (m *ShareWrongTraceDataReturn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShareWrongTraceDataReturn.Merge(m, src)
}
func (m *ShareWrongTraceDataReturn) XXX_Size() int {
	return xxx_messageInfo_ShareWrongTraceDataReturn.Size(m)
}
func (m *ShareWrongTraceDataReturn) XXX_DiscardUnknown() {
	xxx_messageInfo_ShareWrongTraceDataReturn.DiscardUnknown(m)
}

var xxx_messageInfo_ShareWrongTraceDataReturn proto.InternalMessageInfo

func (m *ShareWrongTraceDataReturn) GetWrongTraceDataRequests() []string {
	if m != nil {
		return m.WrongTraceDataRequests
	}
	return nil
}

type TraceData struct {
	TraceId              string   `protobuf:"bytes,1,opt,name=traceId,proto3" json:"traceId,omitempty"`
	Spans                [][]byte `protobuf:"bytes,2,rep,name=spans,proto3" json:"spans,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TraceData) Reset()         { *m = TraceData{} }
func (m *TraceData) String() string { return proto.CompactTextString(m) }
func (*TraceData) ProtoMessage()    {}
func (*TraceData) Descriptor() ([]byte, []int) {
	return fileDescriptor_567c35356db43e2a, []int{2}
}

func (m *TraceData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TraceData.Unmarshal(m, b)
}
func (m *TraceData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TraceData.Marshal(b, m, deterministic)
}
func (m *TraceData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TraceData.Merge(m, src)
}
func (m *TraceData) XXX_Size() int {
	return xxx_messageInfo_TraceData.Size(m)
}
func (m *TraceData) XXX_DiscardUnknown() {
	xxx_messageInfo_TraceData.DiscardUnknown(m)
}

var xxx_messageInfo_TraceData proto.InternalMessageInfo

func (m *TraceData) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

func (m *TraceData) GetSpans() [][]byte {
	if m != nil {
		return m.Spans
	}
	return nil
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_567c35356db43e2a, []int{3}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*WrongTraceDataRequest)(nil), "WrongTraceDataRequest")
	proto.RegisterType((*ShareWrongTraceDataReturn)(nil), "ShareWrongTraceDataReturn")
	proto.RegisterType((*TraceData)(nil), "TraceData")
	proto.RegisterType((*Empty)(nil), "Empty")
}

func init() {
	proto.RegisterFile("rpc/western_queen.proto", fileDescriptor_567c35356db43e2a)
}

var fileDescriptor_567c35356db43e2a = []byte{
	// 243 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x3f, 0x4f, 0xc3, 0x30,
	0x10, 0xc5, 0x6b, 0xaa, 0xb6, 0xca, 0xa9, 0xd3, 0x01, 0x6d, 0xc8, 0x14, 0x79, 0xca, 0x82, 0xf9,
	0x27, 0x75, 0x61, 0x42, 0x82, 0x81, 0x11, 0x07, 0xa9, 0x23, 0x32, 0xcd, 0x09, 0x96, 0x3a, 0xe9,
	0xf9, 0xa2, 0x8a, 0x6f, 0xc6, 0xc7, 0x43, 0x69, 0x20, 0x08, 0x94, 0x8c, 0xf7, 0x9e, 0xfd, 0x9e,
	0x7f, 0x3e, 0x58, 0x72, 0xb5, 0xb9, 0xd8, 0x53, 0x10, 0x62, 0xff, 0xb2, 0xab, 0x89, 0xbc, 0xa9,
	0xb8, 0x94, 0x52, 0x5f, 0xc1, 0xe9, 0x9a, 0x4b, 0xff, 0xf6, 0xcc, 0x6e, 0x43, 0xf7, 0x4e, 0x9c,
	0xa5, 0x5d, 0x4d, 0x41, 0x30, 0x86, 0x99, 0x34, 0xda, 0x63, 0x11, 0xab, 0x54, 0x65, 0x91, 0xfd,
	0x19, 0x75, 0x0e, 0x67, 0xf9, 0xbb, 0x63, 0xfa, 0x7f, 0x4f, 0x6a, 0xf6, 0xb8, 0x82, 0xc5, 0xbe,
	0x2f, 0x2f, 0xc4, 0x2a, 0x1d, 0x67, 0x91, 0x1d, 0x70, 0xf5, 0x2d, 0x44, 0x9d, 0x38, 0xdc, 0x8d,
	0x27, 0x30, 0x09, 0x95, 0xf3, 0x21, 0x3e, 0x4a, 0xc7, 0xd9, 0xdc, 0xb6, 0x83, 0x9e, 0xc1, 0xe4,
	0x61, 0x5b, 0xc9, 0xc7, 0xf5, 0xa7, 0x82, 0xf9, 0xba, 0xa5, 0x7c, 0x6a, 0x20, 0x71, 0x05, 0x98,
	0x93, 0x2f, 0xfe, 0x3e, 0x15, 0x17, 0xa6, 0x97, 0x39, 0x99, 0x9a, 0x43, 0x8c, 0x1e, 0xe1, 0x1d,
	0x2c, 0x2d, 0xb9, 0xa2, 0x87, 0x13, 0xbf, 0x0f, 0x25, 0x89, 0x19, 0xfc, 0x05, 0x3d, 0xba, 0x54,
	0x78, 0x0e, 0xc7, 0x4d, 0x75, 0x67, 0xe5, 0xc2, 0xe4, 0xb6, 0x08, 0xa6, 0x53, 0x7e, 0xfb, 0x32,
	0xf5, 0x3a, 0x3d, 0xec, 0xe3, 0xe6, 0x2b, 0x00, 0x00, 0xff, 0xff, 0xf9, 0x2e, 0x5d, 0xfc, 0xaa,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// WesternQueenClient is the client API for WesternQueen service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WesternQueenClient interface {
	SendWrongTraceData(ctx context.Context, in *WrongTraceDataRequest, opts ...grpc.CallOption) (*Empty, error)
	ReadShareWrongTraceData(ctx context.Context, in *Empty, opts ...grpc.CallOption) (WesternQueen_ReadShareWrongTraceDataClient, error)
	SendTraceDataStream(ctx context.Context, opts ...grpc.CallOption) (WesternQueen_SendTraceDataStreamClient, error)
}

type westernQueenClient struct {
	cc grpc.ClientConnInterface
}

func NewWesternQueenClient(cc grpc.ClientConnInterface) WesternQueenClient {
	return &westernQueenClient{cc}
}

func (c *westernQueenClient) SendWrongTraceData(ctx context.Context, in *WrongTraceDataRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/WesternQueen/SendWrongTraceData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *westernQueenClient) ReadShareWrongTraceData(ctx context.Context, in *Empty, opts ...grpc.CallOption) (WesternQueen_ReadShareWrongTraceDataClient, error) {
	stream, err := c.cc.NewStream(ctx, &_WesternQueen_serviceDesc.Streams[0], "/WesternQueen/ReadShareWrongTraceData", opts...)
	if err != nil {
		return nil, err
	}
	x := &westernQueenReadShareWrongTraceDataClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type WesternQueen_ReadShareWrongTraceDataClient interface {
	Recv() (*ShareWrongTraceDataReturn, error)
	grpc.ClientStream
}

type westernQueenReadShareWrongTraceDataClient struct {
	grpc.ClientStream
}

func (x *westernQueenReadShareWrongTraceDataClient) Recv() (*ShareWrongTraceDataReturn, error) {
	m := new(ShareWrongTraceDataReturn)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *westernQueenClient) SendTraceDataStream(ctx context.Context, opts ...grpc.CallOption) (WesternQueen_SendTraceDataStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_WesternQueen_serviceDesc.Streams[1], "/WesternQueen/SendTraceDataStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &westernQueenSendTraceDataStreamClient{stream}
	return x, nil
}

type WesternQueen_SendTraceDataStreamClient interface {
	Send(*TraceData) error
	CloseAndRecv() (*Empty, error)
	grpc.ClientStream
}

type westernQueenSendTraceDataStreamClient struct {
	grpc.ClientStream
}

func (x *westernQueenSendTraceDataStreamClient) Send(m *TraceData) error {
	return x.ClientStream.SendMsg(m)
}

func (x *westernQueenSendTraceDataStreamClient) CloseAndRecv() (*Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// WesternQueenServer is the server API for WesternQueen service.
type WesternQueenServer interface {
	SendWrongTraceData(context.Context, *WrongTraceDataRequest) (*Empty, error)
	ReadShareWrongTraceData(*Empty, WesternQueen_ReadShareWrongTraceDataServer) error
	SendTraceDataStream(WesternQueen_SendTraceDataStreamServer) error
}

// UnimplementedWesternQueenServer can be embedded to have forward compatible implementations.
type UnimplementedWesternQueenServer struct {
}

func (*UnimplementedWesternQueenServer) SendWrongTraceData(ctx context.Context, req *WrongTraceDataRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendWrongTraceData not implemented")
}
func (*UnimplementedWesternQueenServer) ReadShareWrongTraceData(req *Empty, srv WesternQueen_ReadShareWrongTraceDataServer) error {
	return status.Errorf(codes.Unimplemented, "method ReadShareWrongTraceData not implemented")
}
func (*UnimplementedWesternQueenServer) SendTraceDataStream(srv WesternQueen_SendTraceDataStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method SendTraceDataStream not implemented")
}

func RegisterWesternQueenServer(s *grpc.Server, srv WesternQueenServer) {
	s.RegisterService(&_WesternQueen_serviceDesc, srv)
}

func _WesternQueen_SendWrongTraceData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WrongTraceDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WesternQueenServer).SendWrongTraceData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/WesternQueen/SendWrongTraceData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WesternQueenServer).SendWrongTraceData(ctx, req.(*WrongTraceDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WesternQueen_ReadShareWrongTraceData_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WesternQueenServer).ReadShareWrongTraceData(m, &westernQueenReadShareWrongTraceDataServer{stream})
}

type WesternQueen_ReadShareWrongTraceDataServer interface {
	Send(*ShareWrongTraceDataReturn) error
	grpc.ServerStream
}

type westernQueenReadShareWrongTraceDataServer struct {
	grpc.ServerStream
}

func (x *westernQueenReadShareWrongTraceDataServer) Send(m *ShareWrongTraceDataReturn) error {
	return x.ServerStream.SendMsg(m)
}

func _WesternQueen_SendTraceDataStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WesternQueenServer).SendTraceDataStream(&westernQueenSendTraceDataStreamServer{stream})
}

type WesternQueen_SendTraceDataStreamServer interface {
	SendAndClose(*Empty) error
	Recv() (*TraceData, error)
	grpc.ServerStream
}

type westernQueenSendTraceDataStreamServer struct {
	grpc.ServerStream
}

func (x *westernQueenSendTraceDataStreamServer) SendAndClose(m *Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *westernQueenSendTraceDataStreamServer) Recv() (*TraceData, error) {
	m := new(TraceData)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _WesternQueen_serviceDesc = grpc.ServiceDesc{
	ServiceName: "WesternQueen",
	HandlerType: (*WesternQueenServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendWrongTraceData",
			Handler:    _WesternQueen_SendWrongTraceData_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReadShareWrongTraceData",
			Handler:       _WesternQueen_ReadShareWrongTraceData_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SendTraceDataStream",
			Handler:       _WesternQueen_SendTraceDataStream_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "rpc/western_queen.proto",
}
